"""Shared detail card widgets and presenters."""

from desktop.shared.detail.card import WatchedDetailCard
from desktop.shared.detail.list_delegate import (
    WatchedListItemDelegate,
    _elide_text,
    _load_list_thumb_pixmap,
    fit_poster_pixmap_for_display,
)
from desktop.shared.detail.main_info import (
    build_main_info_items,
    format_votes_display,
    normalize_object_type,
)
from desktop.shared.detail.presenters import (
    build_detail_info_pill_labels,
    build_genre_pill_labels,
    build_meta_pill_items,
    build_meta_pill_labels,
    build_score_ring_item,
    format_final_score,
    format_genre_pill_label,
    format_rating_score_display,
    format_user_score_display,
    get_country_display,
    get_overview_display,
    has_overview_text,
    normalize_final_score,
    score_ring_color_for_final_score,
)
from desktop.shared.detail.posters import (
    format_poster_path_display,
    get_poster_cache_directory,
    open_path_in_shell,
    resolve_local_poster_path,
)
from desktop.shared.detail.profiles import (
    ADD_TITLE_PREVIEW_CARD_PROFILE,
    CANDIDATE_DETAIL_CARD_PROFILE,
    DETAIL_CARD_LAYOUT_PROFILE,
    DetailCardLayoutProfile,
    LIST_ITEM_HEIGHT,
    LIST_ITEM_H_PADDING,
    LIST_ITEM_V_PADDING,
    LIST_TEXT_GAP,
    LIST_THUMB_HEIGHT,
    LIST_THUMB_WIDTH,
    POSTER_BASE_HEIGHT,
    POSTER_BASE_WIDTH,
    POSTER_DISPLAY_SCALE,
    POSTER_HEIGHT,
    POSTER_WIDTH,
)
from desktop.shared.detail.rating_indicator import RatingCircleIndicator
from desktop.shared.detail.types import DetailEntry

__all__ = [
    "ADD_TITLE_PREVIEW_CARD_PROFILE",
    "CANDIDATE_DETAIL_CARD_PROFILE",
    "DETAIL_CARD_LAYOUT_PROFILE",
    "DetailCardLayoutProfile",
    "DetailEntry",
    "LIST_ITEM_HEIGHT",
    "LIST_ITEM_H_PADDING",
    "LIST_ITEM_V_PADDING",
    "LIST_TEXT_GAP",
    "LIST_THUMB_HEIGHT",
    "LIST_THUMB_WIDTH",
    "POSTER_BASE_HEIGHT",
    "POSTER_BASE_WIDTH",
    "POSTER_DISPLAY_SCALE",
    "POSTER_HEIGHT",
    "POSTER_WIDTH",
    "RatingCircleIndicator",
    "WatchedDetailCard",
    "WatchedListItemDelegate",
    "_elide_text",
    "_load_list_thumb_pixmap",
    "build_detail_info_pill_labels",
    "build_genre_pill_labels",
    "build_main_info_items",
    "build_meta_pill_items",
    "build_meta_pill_labels",
    "build_score_ring_item",
    "fit_poster_pixmap_for_display",
    "format_final_score",
    "format_genre_pill_label",
    "format_poster_path_display",
    "format_rating_score_display",
    "format_user_score_display",
    "format_votes_display",
    "get_country_display",
    "get_overview_display",
    "get_poster_cache_directory",
    "has_overview_text",
    "normalize_final_score",
    "normalize_object_type",
    "open_path_in_shell",
    "resolve_local_poster_path",
    "score_ring_color_for_final_score",
]
