"""Shared constants for add-title dialogs."""

from __future__ import annotations

from desktop.theme import build_add_title_dialog_style
from desktop.theme.shell_layout import (
    PREVIEW_CARD_SCROLL_MIN_HEIGHT_PX,
    PREVIEW_DIALOG_HEIGHT_PX,
    PREVIEW_DIALOG_WIDTH_PX,
    SEARCH_DIALOG_HEIGHT_ACTIVE_PX,
    SEARCH_DIALOG_HEIGHT_PX,
    SEARCH_DIALOG_WIDTH_PX,
)

ADD_TITLE_DIALOG_STYLE = build_add_title_dialog_style()

SEARCH_DIALOG_WIDTH = SEARCH_DIALOG_WIDTH_PX
SEARCH_DIALOG_HEIGHT = SEARCH_DIALOG_HEIGHT_PX
SEARCH_DIALOG_HEIGHT_ACTIVE = SEARCH_DIALOG_HEIGHT_ACTIVE_PX
PREVIEW_DIALOG_WIDTH = PREVIEW_DIALOG_WIDTH_PX
PREVIEW_DIALOG_HEIGHT = PREVIEW_DIALOG_HEIGHT_PX
PREVIEW_CARD_SCROLL_MIN_HEIGHT = PREVIEW_CARD_SCROLL_MIN_HEIGHT_PX
