"""Layout constants and scaled geometry for the desktop UI."""

from __future__ import annotations

from desktop.theme.scaling import control_px, detail_px, font_px, layout_px, list_px, poster_px

# Base spacing / padding values at ui_scale 1.0.
SPACING_XSMALL = 2
SPACING_SMALL = 6
SPACING_MEDIUM = 10
SPACING_LARGE = 14
SPACING_XLARGE = 16
SPACING_XXLARGE = 22

ROOT_MARGIN = 14
SECTION_PADDING = 10
CARD_PADDING = 22
OVERVIEW_SECTION_TOP_SPACING = 24
OVERVIEW_TITLE_DIVIDER_SPACING = 12
OVERVIEW_DIVIDER_TEXT_SPACING = 12
OVERVIEW_TEXT_LINE_HEIGHT = 155
INPUT_PADDING_Y = 8
INPUT_PADDING_X = 10
BUTTON_PADDING_Y = 8
BUTTON_PADDING_X = 14

# List row geometry.
LIST_TITLE_BAND_HEIGHT = 32
LIST_META_BAND_HEIGHT = 22
LIST_FALLBACK_WIDTH = 280
LIST_MIN_TEXT_WIDTH = 40
LIST_ROW_INSET_X = 2
LIST_ROW_INSET_Y = 1
LIST_ITEM_HEIGHT_BASE = 84
LIST_THUMB_WIDTH_BASE = 52
LIST_THUMB_HEIGHT_BASE = 78
LIST_ITEM_H_PADDING_BASE = 12
LIST_ITEM_V_PADDING_BASE = 6
LIST_TEXT_GAP_BASE = 12

# Shell layout geometry.
SIDEBAR_MIN_WIDTH = 300
SIDEBAR_MAX_WIDTH = 380
SPLITTER_SIDEBAR_DEFAULT = 380
SPLITTER_DETAIL_DEFAULT = 880
MAIN_TAB_PANE_TOP_LIFT = 36
LEFT_PANEL_TAB_GAP = 10
LEFT_PANEL_TOP_COMPENSATION = MAIN_TAB_PANE_TOP_LIFT + LEFT_PANEL_TAB_GAP
DETAIL_TAB_TOP_MARGIN = 0
WATCHED_TAB_MARGIN = SPACING_XLARGE
WATCHED_TAB_SPACING = SPACING_XLARGE
WATCHED_ADD_TITLE_MIN_HEIGHT = 30
WATCHED_ADD_TITLE_PADDING_Y = 5
WATCHED_SIDEBAR_LABEL_FONT = 15
CANDIDATE_LIST_MIN_WIDTH = 300
CANDIDATE_LIST_MAX_WIDTH = 380
CANDIDATE_ROOT_MARGIN = SPACING_XLARGE
CANDIDATE_ROOT_SPACING = 12
CANDIDATE_LIST_SPACING = 14
CANDIDATE_SORT_ROW_SPACING = 10
CANDIDATE_SPLITTER_LIST_DEFAULT = SPLITTER_SIDEBAR_DEFAULT
CANDIDATE_SPLITTER_DETAIL_DEFAULT = SPLITTER_DETAIL_DEFAULT
CANDIDATE_SORT_COMBO_MAX_WIDTH = 160

# Dialog geometry.
SEARCH_DIALOG_WIDTH = 660
SEARCH_DIALOG_HEIGHT = 154
SEARCH_DIALOG_HEIGHT_ACTIVE = 194
PREVIEW_DIALOG_WIDTH = 600
PREVIEW_DIALOG_HEIGHT = 540
PREVIEW_CARD_SCROLL_MIN_HEIGHT = 260
ADD_TITLE_COMPACT_POSTER_WIDTH = 112
ADD_TITLE_COMPACT_POSTER_HEIGHT = 168
ADD_TITLE_COMPACT_POSTER_RADIUS = 12
ADD_TITLE_COMPACT_CONTENT_GAP = 10
ADD_TITLE_COMPACT_SCORE_WIDGET_SIZE = 68
ADD_TITLE_COMPACT_SCORE_CIRCLE_DIAMETER = 58
SETTINGS_DIALOG_MIN_WIDTH = 360

# Detail card geometry.
DETAIL_HERO_CARD_RADIUS = 24
DETAIL_HERO_CARD_PADDING = 28
DETAIL_HERO_CARD_PADDING_TOP = 12
DETAIL_HERO_MIN_WIDTH = 980
DETAIL_HERO_PREFERRED_MIN_WIDTH = 1200
DETAIL_CONTENT_MAX_WIDTH = 1120
WATCHED_DETAIL_COLLAPSE_WIDTH = SIDEBAR_MIN_WIDTH + DETAIL_HERO_MIN_WIDTH + (2 * WATCHED_TAB_MARGIN)

DETAIL_POSTER_WIDTH = 340
DETAIL_POSTER_HEIGHT = 500
DETAIL_POSTER_RADIUS = 16
DETAIL_POSTER_BORDER_WIDTH = 1
DETAIL_POSTER_RIGHT_GAP = 42

DETAIL_INFO_MIN_WIDTH = 350
DETAIL_INFO_MAX_WIDTH = 760
DETAIL_INFO_COLUMN_MAX_WIDTH = 700
DETAIL_INFO_TOP_OFFSET = 18

DETAIL_TITLE_FONT_SIZE = 32
DETAIL_TITLE_LINE_HEIGHT = 42
DETAIL_TITLE_MAX_LINES = 2

DETAIL_CHIP_HEIGHT = 36
DETAIL_CHIP_RADIUS = 18
DETAIL_CHIP_H_PADDING = 16
DETAIL_CHIP_FONT_SIZE = 15
DETAIL_CHIP_ROW_GAP = 10
DETAIL_CHIP_COL_GAP = 14
DETAIL_CHIP_MAX_ROWS = 2
DETAIL_CHIP_MAX_WIDTH = 210

DETAIL_SCORE_ROW_TOP_GAP = 34
DETAIL_RATING_WIDGET_SIZE = 136
DETAIL_RATING_CIRCLE_DIAMETER = 122
DETAIL_STARS_LEFT_GAP = 28
DETAIL_STAR_SIZE = 36
DETAIL_STAR_GAP = 9

DETAIL_USER_SCORE_BADGE_MIN_WIDTH = 64
DETAIL_USER_SCORE_BADGE_HEIGHT = 34
DETAIL_USER_SCORE_BADGE_RADIUS = 17
DETAIL_USER_SCORE_BADGE_FONT_SIZE = 15
DETAIL_USER_SCORE_BADGE_TOP = 14
DETAIL_USER_SCORE_BADGE_LEFT = 14
DETAIL_USER_SCORE_BADGE_PADDING_X = 9

DETAIL_MAIN_INFO_TOP_GAP = 38
DETAIL_MAIN_INFO_PANEL_RADIUS = 16
DETAIL_MAIN_INFO_PANEL_PADDING_X = 28
DETAIL_MAIN_INFO_PANEL_PADDING_Y = 18
DETAIL_MAIN_INFO_ROW_HEIGHT = 48
DETAIL_MAIN_INFO_ROW_GAP = 10
DETAIL_MAIN_INFO_HEADER_PANEL_GAP = 20
DETAIL_MAIN_INFO_LABEL_WIDTH = 230

DETAIL_OVERVIEW_TOP_GAP = 14
DETAIL_OVERVIEW_LEFT_INSET = 0
DETAIL_OVERVIEW_TITLE_TOP_GAP = 14
DETAIL_OVERVIEW_TEXT_TOP_GAP = 20
DETAIL_OVERVIEW_MAX_LINES_COLLAPSED = 4
DETAIL_OVERVIEW_MAX_WIDTH = DETAIL_POSTER_WIDTH
DETAIL_TITLE_CHIPS_GAP = 30
DETAIL_SCORE_MAIN_INFO_GAP = 24
DETAIL_SECTION_MAX_WIDTH = 920


def px(value: int | float) -> int:
    """Compatibility wrapper for general layout geometry."""
    return layout_px(value)


# Scaled shell/dialog constants frozen at import time.
SIDEBAR_MIN_WIDTH_PX = list_px(SIDEBAR_MIN_WIDTH)
SIDEBAR_MAX_WIDTH_PX = list_px(SIDEBAR_MAX_WIDTH)
SPLITTER_SIDEBAR_DEFAULT_PX = list_px(SPLITTER_SIDEBAR_DEFAULT)
SPLITTER_DETAIL_DEFAULT_PX = layout_px(SPLITTER_DETAIL_DEFAULT)
MAIN_TAB_PANE_TOP_LIFT_PX = layout_px(MAIN_TAB_PANE_TOP_LIFT)
LEFT_PANEL_TOP_COMPENSATION_PX = layout_px(LEFT_PANEL_TOP_COMPENSATION)
DETAIL_TAB_TOP_MARGIN_PX = layout_px(DETAIL_TAB_TOP_MARGIN)
WATCHED_TAB_MARGIN_PX = layout_px(WATCHED_TAB_MARGIN)
WATCHED_TAB_SPACING_PX = layout_px(WATCHED_TAB_SPACING)
WATCHED_DETAIL_COLLAPSE_WIDTH_PX = layout_px(WATCHED_DETAIL_COLLAPSE_WIDTH)

CANDIDATE_LIST_MIN_WIDTH_PX = list_px(CANDIDATE_LIST_MIN_WIDTH)
CANDIDATE_LIST_MAX_WIDTH_PX = list_px(CANDIDATE_LIST_MAX_WIDTH)
CANDIDATE_ROOT_MARGIN_PX = layout_px(CANDIDATE_ROOT_MARGIN)
CANDIDATE_ROOT_SPACING_PX = layout_px(CANDIDATE_ROOT_SPACING)
CANDIDATE_LIST_SPACING_PX = layout_px(CANDIDATE_LIST_SPACING)
CANDIDATE_SORT_ROW_SPACING_PX = layout_px(CANDIDATE_SORT_ROW_SPACING)
CANDIDATE_SORT_COMBO_MAX_WIDTH_PX = control_px(CANDIDATE_SORT_COMBO_MAX_WIDTH)
CANDIDATE_SPLITTER_LIST_DEFAULT_PX = list_px(CANDIDATE_SPLITTER_LIST_DEFAULT)
CANDIDATE_SPLITTER_DETAIL_DEFAULT_PX = layout_px(CANDIDATE_SPLITTER_DETAIL_DEFAULT)

SEARCH_DIALOG_WIDTH_PX = layout_px(SEARCH_DIALOG_WIDTH)
SEARCH_DIALOG_HEIGHT_PX = layout_px(SEARCH_DIALOG_HEIGHT)
SEARCH_DIALOG_HEIGHT_ACTIVE_PX = layout_px(SEARCH_DIALOG_HEIGHT_ACTIVE)
PREVIEW_DIALOG_WIDTH_PX = layout_px(PREVIEW_DIALOG_WIDTH)
PREVIEW_DIALOG_HEIGHT_PX = layout_px(PREVIEW_DIALOG_HEIGHT)
PREVIEW_CARD_SCROLL_MIN_HEIGHT_PX = layout_px(PREVIEW_CARD_SCROLL_MIN_HEIGHT)
SETTINGS_DIALOG_MIN_WIDTH_PX = layout_px(SETTINGS_DIALOG_MIN_WIDTH)


__all__ = [name for name in globals() if name.isupper() or name.endswith("_px") or name == "px"]
