"""Scaled shell layout constants derived from theme tokens."""

from __future__ import annotations

from desktop.theme.scaling import control_px, layout_px, list_px
from desktop.theme.tokens import (
    CANDIDATE_LIST_MAX_WIDTH,
    CANDIDATE_LIST_MIN_WIDTH,
    CANDIDATE_LIST_SPACING,
    CANDIDATE_ROOT_MARGIN,
    CANDIDATE_ROOT_SPACING,
    CANDIDATE_SORT_COMBO_MAX_WIDTH,
    CANDIDATE_SORT_ROW_SPACING,
    CANDIDATE_SPLITTER_DETAIL_DEFAULT,
    CANDIDATE_SPLITTER_LIST_DEFAULT,
    PREVIEW_CARD_SCROLL_MIN_HEIGHT,
    PREVIEW_DIALOG_HEIGHT,
    PREVIEW_DIALOG_WIDTH,
    SEARCH_DIALOG_HEIGHT,
    SEARCH_DIALOG_HEIGHT_ACTIVE,
    SEARCH_DIALOG_WIDTH,
    SETTINGS_DIALOG_MIN_WIDTH,
    MAIN_TAB_PANE_TOP_LIFT,
    SIDEBAR_MAX_WIDTH,
    SIDEBAR_MIN_WIDTH,
    SPLITTER_DETAIL_DEFAULT,
    SPLITTER_SIDEBAR_DEFAULT,
    LEFT_PANEL_TOP_COMPENSATION,
    DETAIL_TAB_TOP_MARGIN,
    WATCHED_TAB_MARGIN,
    WATCHED_TAB_SPACING,
)

SIDEBAR_MIN_WIDTH_PX = list_px(SIDEBAR_MIN_WIDTH)
SIDEBAR_MAX_WIDTH_PX = list_px(SIDEBAR_MAX_WIDTH)
SPLITTER_SIDEBAR_DEFAULT_PX = list_px(SPLITTER_SIDEBAR_DEFAULT)
SPLITTER_DETAIL_DEFAULT_PX = layout_px(SPLITTER_DETAIL_DEFAULT)
MAIN_TAB_PANE_TOP_LIFT_PX = layout_px(MAIN_TAB_PANE_TOP_LIFT)
LEFT_PANEL_TOP_COMPENSATION_PX = layout_px(LEFT_PANEL_TOP_COMPENSATION)
DETAIL_TAB_TOP_MARGIN_PX = layout_px(DETAIL_TAB_TOP_MARGIN)
WATCHED_TAB_MARGIN_PX = layout_px(WATCHED_TAB_MARGIN)
WATCHED_TAB_SPACING_PX = layout_px(WATCHED_TAB_SPACING)

CANDIDATE_LIST_MIN_WIDTH_PX = list_px(CANDIDATE_LIST_MIN_WIDTH)
CANDIDATE_LIST_MAX_WIDTH_PX = list_px(CANDIDATE_LIST_MAX_WIDTH)
CANDIDATE_ROOT_MARGIN_PX = layout_px(CANDIDATE_ROOT_MARGIN)
CANDIDATE_ROOT_SPACING_PX = layout_px(CANDIDATE_ROOT_SPACING)
CANDIDATE_LIST_SPACING_PX = layout_px(CANDIDATE_LIST_SPACING)
CANDIDATE_SORT_ROW_SPACING_PX = layout_px(CANDIDATE_SORT_ROW_SPACING)
CANDIDATE_SORT_COMBO_MAX_WIDTH_PX = control_px(CANDIDATE_SORT_COMBO_MAX_WIDTH)
CANDIDATE_SPLITTER_LIST_DEFAULT_PX = list_px(CANDIDATE_SPLITTER_LIST_DEFAULT)
CANDIDATE_SPLITTER_DETAIL_DEFAULT_PX = layout_px(CANDIDATE_SPLITTER_DETAIL_DEFAULT)

SEARCH_DIALOG_WIDTH_PX = layout_px(SEARCH_DIALOG_WIDTH)
SEARCH_DIALOG_HEIGHT_PX = layout_px(SEARCH_DIALOG_HEIGHT)
SEARCH_DIALOG_HEIGHT_ACTIVE_PX = layout_px(SEARCH_DIALOG_HEIGHT_ACTIVE)
PREVIEW_DIALOG_WIDTH_PX = layout_px(PREVIEW_DIALOG_WIDTH)
PREVIEW_DIALOG_HEIGHT_PX = layout_px(PREVIEW_DIALOG_HEIGHT)
PREVIEW_CARD_SCROLL_MIN_HEIGHT_PX = layout_px(PREVIEW_CARD_SCROLL_MIN_HEIGHT)
SETTINGS_DIALOG_MIN_WIDTH_PX = layout_px(SETTINGS_DIALOG_MIN_WIDTH)
