"""Visual style tokens for the PyQt desktop GUI."""

from __future__ import annotations


# Colors
COLOR_BG = "#0f0f10"
COLOR_SURFACE = "#111113"
COLOR_CARD = "#171719"
COLOR_CARD_ALT = "#1c1c1f"
COLOR_BORDER = "#2a2a2e"
COLOR_BORDER_HOVER = "#3f3f46"
COLOR_HOVER = "#202024"
COLOR_CONTROL_HOVER = "#27272a"

COLOR_TEXT = "#f4f4f5"
COLOR_TEXT_SECONDARY = "#a1a1aa"
COLOR_TEXT_MUTED = "#71717a"
COLOR_TEXT_SOFT = "#d4d4d8"
COLOR_TEXT_CHIP = "#c7c7ce"

COLOR_ACCENT = "#10a37f"
COLOR_ACCENT_HOVER = "#13b98f"
COLOR_ACCENT_SOFT = "#1f3f36"
COLOR_ACCENT_PLOT_HOVER = "#35caa5"
COLOR_ACCENT_PLOT_FILL = "rgba(16, 163, 127, 0.22)"

COLOR_ADD_BUTTON = "#1f4d3d"
COLOR_ADD_BUTTON_BORDER = "#1a4234"
COLOR_ADD_BUTTON_TOP = "#2a6b55"
COLOR_ADD_BUTTON_HOVER = "#266552"
COLOR_ADD_BUTTON_HOVER_TOP = "#327a62"

COLOR_DELETE_BUTTON = "#7a3f3f"
COLOR_DELETE_BUTTON_HOVER = "#8f4a4a"

COLOR_STALE_BG = "#3a1f1f"
COLOR_STALE_BORDER = "#8f4a4a"
COLOR_STALE_TEXT = "#fecaca"

COLOR_IMDB_ACCENT = "#8b949e"
COLOR_KP_ACCENT = "#87978f"

COLOR_DETAIL_HERO_BG_TOP = "#101722"
COLOR_DETAIL_HERO_BG_BOTTOM = "#0b0f16"
COLOR_DETAIL_HERO_BORDER = "#2e3a46"
COLOR_DETAIL_HERO_BORDER_SOFT = "rgba(255, 255, 255, 0.08)"
COLOR_DETAIL_WARM_TEXT = "#fff7ed"
COLOR_DETAIL_GOLD = "#f5c451"
COLOR_DETAIL_GOLD_SOFT = "#d6bd8d"
COLOR_DETAIL_GLASS = "rgba(18, 25, 34, 190)"
COLOR_DETAIL_GLASS_SOFT = "rgba(22, 30, 40, 150)"


# Typography
FONT_FAMILY = "Segoe UI"
FONT_FAMILY_FALLBACK = "Arial, sans-serif"
FONT_FAMILY_QSS = f'"{FONT_FAMILY}", {FONT_FAMILY_FALLBACK}'

FONT_APP = 13
FONT_BASE = 14
FONT_SMALL = 13
FONT_TINY = 12
FONT_SECTION = 16
FONT_TITLE = 24
FONT_TITLE_LARGE = 26
FONT_DIALOG_TITLE = 18
FONT_KPI_VALUE = 26
FONT_DENSE_SCORE = 22
FONT_OVERVIEW_TITLE = 20
FONT_OVERVIEW_TEXT = 16
FONT_RATING_VALUE_POINT = 16
FONT_RATING_LABEL_POINT = 8


# Radius
RADIUS_CARD = 16
RADIUS_CARD_LARGE = 18
RADIUS_CHIP = 12
RADIUS_INPUT = 12
RADIUS_BUTTON = 12
RADIUS_BUTTON_SMALL = 8
RADIUS_LIST_ITEM = 10
RADIUS_SCROLLBAR = 5
RADIUS_BAR = 6


# Spacing / padding
SPACING_XSMALL = 2
SPACING_SMALL = 6
SPACING_MEDIUM = 10
SPACING_LARGE = 14
SPACING_XLARGE = 16
SPACING_XXLARGE = 22

ROOT_MARGIN = 14
SECTION_PADDING = 10
CARD_PADDING = 22
OVERVIEW_SECTION_TOP_SPACING = 36
OVERVIEW_TITLE_DIVIDER_SPACING = 12
OVERVIEW_DIVIDER_TEXT_SPACING = 12
OVERVIEW_TEXT_LINE_HEIGHT = 155
INPUT_PADDING_Y = 8
INPUT_PADDING_X = 10
BUTTON_PADDING_Y = 8
BUTTON_PADDING_X = 14

# Cinematic detail hero contract tokens
DETAIL_HERO_CARD_RADIUS = 24
DETAIL_HERO_CARD_PADDING = 28
DETAIL_HERO_MIN_WIDTH = 980
DETAIL_HERO_PREFERRED_MIN_WIDTH = 1200

DETAIL_POSTER_WIDTH = 328
DETAIL_POSTER_HEIGHT = 482
DETAIL_POSTER_RADIUS = 20
DETAIL_POSTER_RIGHT_GAP = 36

DETAIL_INFO_MIN_WIDTH = 560
DETAIL_INFO_MAX_WIDTH = 760

DETAIL_TITLE_FONT_FAMILY = "Georgia"
DETAIL_TITLE_FONT_FALLBACK = "Times New Roman"
DETAIL_TITLE_FONT_SIZE = 34
DETAIL_TITLE_LINE_HEIGHT = 42
DETAIL_TITLE_MAX_LINES = 2

DETAIL_CHIP_HEIGHT = 32
DETAIL_CHIP_RADIUS = 16
DETAIL_CHIP_H_PADDING = 18
DETAIL_CHIP_ROW_GAP = 8
DETAIL_CHIP_COL_GAP = 12
DETAIL_CHIP_MAX_ROWS = 2
DETAIL_CHIP_MAX_WIDTH = 150

DETAIL_SCORE_ROW_TOP_GAP = 30
DETAIL_RATING_WIDGET_SIZE = 124
DETAIL_RATING_CIRCLE_DIAMETER = 112
DETAIL_STARS_LEFT_GAP = 44
DETAIL_STAR_SIZE = 32
DETAIL_STAR_GAP = 8

DETAIL_USER_SCORE_BADGE_MIN_WIDTH = 72
DETAIL_USER_SCORE_BADGE_HEIGHT = 36
DETAIL_USER_SCORE_BADGE_RADIUS = 18
DETAIL_USER_SCORE_BADGE_TOP = 14
DETAIL_USER_SCORE_BADGE_RIGHT = 14
DETAIL_USER_SCORE_BADGE_PADDING_X = 12

DETAIL_MAIN_INFO_TOP_GAP = 34
DETAIL_MAIN_INFO_PANEL_RADIUS = 14
DETAIL_MAIN_INFO_PANEL_PADDING_X = 24
DETAIL_MAIN_INFO_PANEL_PADDING_Y = 16
DETAIL_MAIN_INFO_ROW_HEIGHT = 48
DETAIL_MAIN_INFO_LABEL_WIDTH = 210

DETAIL_OVERVIEW_TOP_GAP = 34
DETAIL_OVERVIEW_LEFT_INSET = 0
DETAIL_OVERVIEW_TITLE_TOP_GAP = 24
DETAIL_OVERVIEW_TEXT_TOP_GAP = 18
DETAIL_OVERVIEW_MAX_LINES_COLLAPSED = 4


TRANSPARENT_STYLE = "background: transparent;"

__all__ = [
    "COLOR_BG",
    "COLOR_SURFACE",
    "COLOR_CARD",
    "COLOR_CARD_ALT",
    "COLOR_BORDER",
    "COLOR_BORDER_HOVER",
    "COLOR_HOVER",
    "COLOR_CONTROL_HOVER",
    "COLOR_TEXT",
    "COLOR_TEXT_SECONDARY",
    "COLOR_TEXT_MUTED",
    "COLOR_TEXT_SOFT",
    "COLOR_TEXT_CHIP",
    "COLOR_ACCENT",
    "COLOR_ACCENT_HOVER",
    "COLOR_ACCENT_SOFT",
    "COLOR_ACCENT_PLOT_HOVER",
    "COLOR_ACCENT_PLOT_FILL",
    "COLOR_ADD_BUTTON",
    "COLOR_ADD_BUTTON_BORDER",
    "COLOR_ADD_BUTTON_TOP",
    "COLOR_ADD_BUTTON_HOVER",
    "COLOR_ADD_BUTTON_HOVER_TOP",
    "COLOR_DELETE_BUTTON",
    "COLOR_DELETE_BUTTON_HOVER",
    "COLOR_STALE_BG",
    "COLOR_STALE_BORDER",
    "COLOR_STALE_TEXT",
    "COLOR_IMDB_ACCENT",
    "COLOR_KP_ACCENT",
    "COLOR_DETAIL_HERO_BG_TOP",
    "COLOR_DETAIL_HERO_BG_BOTTOM",
    "COLOR_DETAIL_HERO_BORDER",
    "COLOR_DETAIL_HERO_BORDER_SOFT",
    "COLOR_DETAIL_WARM_TEXT",
    "COLOR_DETAIL_GOLD",
    "COLOR_DETAIL_GOLD_SOFT",
    "COLOR_DETAIL_GLASS",
    "COLOR_DETAIL_GLASS_SOFT",
    "FONT_FAMILY",
    "FONT_FAMILY_FALLBACK",
    "FONT_FAMILY_QSS",
    "FONT_APP",
    "FONT_BASE",
    "FONT_SMALL",
    "FONT_TINY",
    "FONT_SECTION",
    "FONT_TITLE",
    "FONT_TITLE_LARGE",
    "FONT_DIALOG_TITLE",
    "FONT_KPI_VALUE",
    "FONT_DENSE_SCORE",
    "FONT_OVERVIEW_TITLE",
    "FONT_OVERVIEW_TEXT",
    "FONT_RATING_VALUE_POINT",
    "FONT_RATING_LABEL_POINT",
    "RADIUS_CARD",
    "RADIUS_CARD_LARGE",
    "RADIUS_CHIP",
    "RADIUS_INPUT",
    "RADIUS_BUTTON",
    "RADIUS_BUTTON_SMALL",
    "RADIUS_LIST_ITEM",
    "RADIUS_SCROLLBAR",
    "RADIUS_BAR",
    "SPACING_XSMALL",
    "SPACING_SMALL",
    "SPACING_MEDIUM",
    "SPACING_LARGE",
    "SPACING_XLARGE",
    "SPACING_XXLARGE",
    "ROOT_MARGIN",
    "SECTION_PADDING",
    "CARD_PADDING",
    "OVERVIEW_SECTION_TOP_SPACING",
    "OVERVIEW_TITLE_DIVIDER_SPACING",
    "OVERVIEW_DIVIDER_TEXT_SPACING",
    "OVERVIEW_TEXT_LINE_HEIGHT",
    "INPUT_PADDING_Y",
    "INPUT_PADDING_X",
    "BUTTON_PADDING_Y",
    "BUTTON_PADDING_X",
    "DETAIL_HERO_CARD_RADIUS",
    "DETAIL_HERO_CARD_PADDING",
    "DETAIL_HERO_MIN_WIDTH",
    "DETAIL_HERO_PREFERRED_MIN_WIDTH",
    "DETAIL_POSTER_WIDTH",
    "DETAIL_POSTER_HEIGHT",
    "DETAIL_POSTER_RADIUS",
    "DETAIL_POSTER_RIGHT_GAP",
    "DETAIL_INFO_MIN_WIDTH",
    "DETAIL_INFO_MAX_WIDTH",
    "DETAIL_TITLE_FONT_FAMILY",
    "DETAIL_TITLE_FONT_FALLBACK",
    "DETAIL_TITLE_FONT_SIZE",
    "DETAIL_TITLE_LINE_HEIGHT",
    "DETAIL_TITLE_MAX_LINES",
    "DETAIL_CHIP_HEIGHT",
    "DETAIL_CHIP_RADIUS",
    "DETAIL_CHIP_H_PADDING",
    "DETAIL_CHIP_ROW_GAP",
    "DETAIL_CHIP_COL_GAP",
    "DETAIL_CHIP_MAX_ROWS",
    "DETAIL_CHIP_MAX_WIDTH",
    "DETAIL_SCORE_ROW_TOP_GAP",
    "DETAIL_RATING_WIDGET_SIZE",
    "DETAIL_RATING_CIRCLE_DIAMETER",
    "DETAIL_STARS_LEFT_GAP",
    "DETAIL_STAR_SIZE",
    "DETAIL_STAR_GAP",
    "DETAIL_USER_SCORE_BADGE_MIN_WIDTH",
    "DETAIL_USER_SCORE_BADGE_HEIGHT",
    "DETAIL_USER_SCORE_BADGE_RADIUS",
    "DETAIL_USER_SCORE_BADGE_TOP",
    "DETAIL_USER_SCORE_BADGE_RIGHT",
    "DETAIL_USER_SCORE_BADGE_PADDING_X",
    "DETAIL_MAIN_INFO_TOP_GAP",
    "DETAIL_MAIN_INFO_PANEL_RADIUS",
    "DETAIL_MAIN_INFO_PANEL_PADDING_X",
    "DETAIL_MAIN_INFO_PANEL_PADDING_Y",
    "DETAIL_MAIN_INFO_ROW_HEIGHT",
    "DETAIL_MAIN_INFO_LABEL_WIDTH",
    "DETAIL_OVERVIEW_TOP_GAP",
    "DETAIL_OVERVIEW_LEFT_INSET",
    "DETAIL_OVERVIEW_TITLE_TOP_GAP",
    "DETAIL_OVERVIEW_TEXT_TOP_GAP",
    "DETAIL_OVERVIEW_MAX_LINES_COLLAPSED",
    "TRANSPARENT_STYLE",
]
