"""Visual style tokens for the PyQt desktop GUI."""

from __future__ import annotations

from desktop.theme.scaling import (
    control_px as _control_px,
    detail_px as _detail_px,
    font_px as _font_px,
    layout_px as _layout_px,
    list_px as _list_px,
    poster_px as _poster_px,
)


# Colors
COLOR_BG = "#050B16"
COLOR_SURFACE = "#07101D"
COLOR_CARD = "#0D1726"
COLOR_CARD_ALT = "#111D2E"
COLOR_CARD_ELEVATED = "#142238"
COLOR_HOVER = "#132238"
COLOR_CONTROL_HOVER = "#17283F"

COLOR_BORDER = "#1D2B40"
COLOR_BORDER_HOVER = "#2D4562"
COLOR_BORDER_ACTIVE = "#0EA5D8"
COLOR_DIVIDER = "#1A293C"

COLOR_TEXT = "#F5F7FB"
COLOR_TEXT_SECONDARY = "#B8C2D3"
COLOR_TEXT_MUTED = "#78879B"
COLOR_TEXT_SOFT = "#D7DEE9"
COLOR_TEXT_CHIP = "#BBC6D6"
COLOR_TEXT_INVERTED = "#050B16"

COLOR_ACCENT = "#0EA5D8"
COLOR_ACCENT_HOVER = "#22D3C5"
COLOR_ACCENT_SOFT = "#0B3345"
COLOR_ACCENT_PLOT_HOVER = "#2ADBC9"
COLOR_ACCENT_PLOT_FILL = "rgba(14, 165, 216, 0.22)"

COLOR_SELECTED_BG = "#073A58"
COLOR_SELECTED_BORDER = COLOR_ACCENT
COLOR_FOCUS_BORDER = COLOR_ACCENT

COLOR_ADD_BUTTON = "#0B5F92"
COLOR_ADD_BUTTON_BORDER = "#0E7EB8"
COLOR_ADD_BUTTON_TOP = "#0EA5D8"
COLOR_ADD_BUTTON_HOVER = "#0D78B8"
COLOR_ADD_BUTTON_HOVER_TOP = "#22BCE0"

COLOR_RATING = "#F5B82E"
COLOR_RATING_HOVER = "#FFC83D"
COLOR_STAR_ACTIVE = "#F5B82E"
COLOR_STAR_INACTIVE = "#37404D"
COLOR_SCORE_BADGE_BG = "#0B1726"
COLOR_SCORE_BADGE_BORDER = "#1D2B40"

COLOR_SUCCESS = "#2ADBC9"
COLOR_SUCCESS_SOFT = "#0B383A"

COLOR_DELETE_BUTTON = "#6F2E3A"
COLOR_DELETE_BUTTON_HOVER = "#8A3A48"

COLOR_STALE_BG = "#351C26"
COLOR_STALE_BORDER = "#8A3A48"
COLOR_STALE_TEXT = "#F4B8C2"

COLOR_IMDB_ACCENT = "#8FA2B7"
COLOR_KP_ACCENT = "#9CB2C8"

COLOR_DETAIL_HERO_BG_TOP = "#0D1726"
COLOR_DETAIL_HERO_BG_BOTTOM = "#07101D"
COLOR_DETAIL_HERO_BG_END = "#050B16"
COLOR_DETAIL_HERO_BORDER = "#1D2B40"
COLOR_DETAIL_HERO_BORDER_SOFT = "rgba(45, 69, 98, 0.42)"
COLOR_DETAIL_TITLE = COLOR_TEXT
COLOR_DETAIL_SECTION_HEADER = COLOR_TEXT_SECONDARY
COLOR_DETAIL_SECTION_DIVIDER = COLOR_ACCENT
COLOR_DETAIL_LABEL = COLOR_TEXT_SECONDARY
COLOR_DETAIL_VALUE = COLOR_TEXT
COLOR_DETAIL_OVERVIEW_TEXT = COLOR_TEXT_SOFT
COLOR_DETAIL_GLASS = "rgba(13, 23, 38, 210)"
COLOR_DETAIL_GLASS_SOFT = "rgba(17, 29, 46, 170)"
COLOR_DETAIL_ACTION_BG = "rgba(11, 23, 38, 210)"
COLOR_DETAIL_ACTION_BG_HOVER = "rgba(20, 34, 56, 230)"
COLOR_DETAIL_ACTION_BG_DISABLED = "rgba(11, 23, 38, 150)"
COLOR_DETAIL_CHIP_BG = "rgba(17, 29, 46, 0.78)"
COLOR_DETAIL_CHIP_BORDER = "rgba(45, 69, 98, 0.76)"

# Film visual mode palette from `.codex-visual-film-card/THEME_BRIEF.md`.
FILM_WINDOW_BG = "#050B14"
FILM_SURFACE_0 = "#071322"
FILM_SURFACE_1 = "#0A182A"
FILM_SURFACE_2 = "#0B1A2D"
FILM_BORDER_WEAK = "#17314F"
FILM_BORDER = "#1E4B78"
FILM_BORDER_STRONG = "#2EA8FF"
FILM_ACCENT = "#2EA8FF"
FILM_ACCENT_HOVER = "#35D7F2"
FILM_ACCENT_PRESSED = "#477DFF"
FILM_ACCENT_DIM = "#0B3558"
FILM_TEXT = "#F4F8FF"
FILM_TEXT_SUBTLE = "#C9D6EA"
FILM_TEXT_MUTED = "#8798B3"
FILM_CHIP_BG = "#0B1E34"
FILM_CHIP_BORDER = "#22517F"
FILM_CHIP_TEXT = "#DCEAFF"
FILM_MOVIE_BADGE_BG = "#0B2542"
FILM_MOVIE_BADGE_BORDER = "#2EA8FF"
FILM_MOVIE_BADGE_TEXT = "#EAF6FF"
FILM_SERIES_BADGE_BG = "#082F3A"
FILM_SERIES_BADGE_BORDER = "#35D7F2"
FILM_SERIES_BADGE_TEXT = "#E7FCFF"
FILM_RATING_TRACK = "#17314F"
FILM_RATING_VALUE = "#2EA8FF"
FILM_STAR_ON = "#35AFFF"
FILM_STAR_OFF = "#2A374A"
FILM_SCROLLBAR_BG = "#071322"
FILM_SCROLLBAR_HANDLE = "#1E4B78"
FILM_SCROLLBAR_HANDLE_HOVER = "#2EA8FF"

FILM_COLORS = {
    "window_bg": FILM_WINDOW_BG,
    "surface_0": FILM_SURFACE_0,
    "surface_1": FILM_SURFACE_1,
    "surface_2": FILM_SURFACE_2,
    "border_weak": FILM_BORDER_WEAK,
    "border": FILM_BORDER,
    "border_strong": FILM_BORDER_STRONG,
    "accent": FILM_ACCENT,
    "accent_hover": FILM_ACCENT_HOVER,
    "accent_pressed": FILM_ACCENT_PRESSED,
    "accent_dim": FILM_ACCENT_DIM,
    "text": FILM_TEXT,
    "text_subtle": FILM_TEXT_SUBTLE,
    "text_muted": FILM_TEXT_MUTED,
    "chip_bg": FILM_CHIP_BG,
    "chip_border": FILM_CHIP_BORDER,
    "chip_text": FILM_CHIP_TEXT,
    "movie_badge_bg": FILM_MOVIE_BADGE_BG,
    "movie_badge_border": FILM_MOVIE_BADGE_BORDER,
    "movie_badge_text": FILM_MOVIE_BADGE_TEXT,
    "series_badge_bg": FILM_SERIES_BADGE_BG,
    "series_badge_border": FILM_SERIES_BADGE_BORDER,
    "series_badge_text": FILM_SERIES_BADGE_TEXT,
    "rating_track": FILM_RATING_TRACK,
    "rating_value": FILM_RATING_VALUE,
    "star_on": FILM_STAR_ON,
    "star_off": FILM_STAR_OFF,
    "scrollbar_bg": FILM_SCROLLBAR_BG,
    "scrollbar_handle": FILM_SCROLLBAR_HANDLE,
    "scrollbar_handle_hover": FILM_SCROLLBAR_HANDLE_HOVER,
}


# Typography
FONT_FAMILY = "Segoe UI"
FONT_FAMILY_FALLBACK = "Arial, sans-serif"
FONT_FAMILY_QSS = f'"{FONT_FAMILY}", {FONT_FAMILY_FALLBACK}'

FONT_APP = 14
FONT_BASE = 14
FONT_SMALL = 14
FONT_TINY = 13
FONT_SECTION = 16
FONT_TITLE = 24
FONT_TITLE_LARGE = 26
FONT_DIALOG_TITLE = 18
FONT_KPI_VALUE = 26
FONT_DENSE_SCORE = 22
FONT_OVERVIEW_TITLE = 20
FONT_OVERVIEW_TEXT = 16
FONT_RATING_VALUE_POINT = 16
FONT_RATING_LABEL_POINT = 8
FONT_DETAIL_MAIN_INFO_HEADER = 17
FONT_DETAIL_MAIN_INFO_LABEL = 17
FONT_DETAIL_MAIN_INFO_VALUE = 18
FONT_DETAIL_OVERVIEW_TEXT = 19


# Radius
RADIUS_CARD = 16
RADIUS_CARD_LARGE = 18
RADIUS_CHIP = 12
RADIUS_INPUT = 12
RADIUS_BUTTON = 12
RADIUS_BUTTON_SMALL = 8
RADIUS_LIST_ITEM = 10
RADIUS_SCROLLBAR = 5
RADIUS_BAR = 6


# Spacing / padding
SPACING_XSMALL = 2
SPACING_SMALL = 6
SPACING_MEDIUM = 10
SPACING_LARGE = 14
SPACING_XLARGE = 16
SPACING_XXLARGE = 22

ROOT_MARGIN = 14
SECTION_PADDING = 10
CARD_PADDING = 22
OVERVIEW_SECTION_TOP_SPACING = 24
OVERVIEW_TITLE_DIVIDER_SPACING = 12
OVERVIEW_DIVIDER_TEXT_SPACING = 12
OVERVIEW_TEXT_LINE_HEIGHT = 155
INPUT_PADDING_Y = 8
INPUT_PADDING_X = 10
BUTTON_PADDING_Y = 8
BUTTON_PADDING_X = 14

DETAIL_RATING_RING_VALUE_FONT_MIN = 24
DETAIL_RATING_RING_LABEL_FONT_MIN = 10

# List row typography (base values at ui_scale 1.0)
LIST_TITLE_FONT_SIZE = FONT_BASE
LIST_META_FONT_SIZE = FONT_TINY
LIST_PLACEHOLDER_FONT_SIZE = 11
LIST_TITLE_BAND_HEIGHT = 32
LIST_META_BAND_HEIGHT = 22
LIST_FALLBACK_WIDTH = 280
LIST_CARD_CORNER_RADIUS = RADIUS_LIST_ITEM
LIST_THUMB_CORNER_RADIUS = RADIUS_BAR
LIST_MIN_TEXT_WIDTH = 40
LIST_ROW_INSET_X = 2
LIST_ROW_INSET_Y = 1
LIST_ITEM_HEIGHT_BASE = 84
LIST_THUMB_WIDTH_BASE = 52
LIST_THUMB_HEIGHT_BASE = 78
LIST_ITEM_H_PADDING_BASE = 12
LIST_ITEM_V_PADDING_BASE = 6
LIST_TEXT_GAP_BASE = 12

# Shell layout (base values at ui_scale 1.0)
SIDEBAR_MIN_WIDTH = 300
SIDEBAR_MAX_WIDTH = 380
SPLITTER_SIDEBAR_DEFAULT = 380
SPLITTER_DETAIL_DEFAULT = 880
MAIN_TAB_PANE_TOP_LIFT = 36
LEFT_PANEL_TAB_GAP = 10
LEFT_PANEL_TOP_COMPENSATION = MAIN_TAB_PANE_TOP_LIFT + LEFT_PANEL_TAB_GAP
DETAIL_TAB_TOP_MARGIN = 0
WATCHED_TAB_MARGIN = SPACING_XLARGE
WATCHED_TAB_SPACING = SPACING_XLARGE
WATCHED_ADD_TITLE_MIN_HEIGHT = 30
WATCHED_ADD_TITLE_PADDING_Y = 5
WATCHED_SIDEBAR_LABEL_FONT = FONT_BASE + 1
CANDIDATE_LIST_MIN_WIDTH = 300
CANDIDATE_LIST_MAX_WIDTH = 380
CANDIDATE_ROOT_MARGIN = SPACING_XLARGE
CANDIDATE_ROOT_SPACING = 12
CANDIDATE_LIST_SPACING = 14
CANDIDATE_SORT_ROW_SPACING = 10
CANDIDATE_SPLITTER_LIST_DEFAULT = CANDIDATE_LIST_MAX_WIDTH
CANDIDATE_SPLITTER_DETAIL_DEFAULT = 800
CANDIDATE_SORT_COMBO_MAX_WIDTH = 160

# Dialog geometry (base values at ui_scale 1.0)
SEARCH_DIALOG_WIDTH = 660
SEARCH_DIALOG_HEIGHT = 154
SEARCH_DIALOG_HEIGHT_ACTIVE = 194
PREVIEW_DIALOG_WIDTH = 600
PREVIEW_DIALOG_HEIGHT = 540
PREVIEW_CARD_SCROLL_MIN_HEIGHT = 260
ADD_TITLE_COMPACT_POSTER_WIDTH = 112
ADD_TITLE_COMPACT_POSTER_HEIGHT = 168
ADD_TITLE_COMPACT_POSTER_RADIUS = 12
ADD_TITLE_COMPACT_CONTENT_GAP = 10
ADD_TITLE_COMPACT_SCORE_WIDGET_SIZE = 68
ADD_TITLE_COMPACT_SCORE_CIRCLE_DIAMETER = 58
SETTINGS_DIALOG_MIN_WIDTH = 360

# Cinematic detail hero contract tokens
DETAIL_HERO_CARD_RADIUS = 24
DETAIL_HERO_CARD_PADDING = 28
DETAIL_HERO_CARD_PADDING_TOP = 12
DETAIL_HERO_MIN_WIDTH = 980
DETAIL_HERO_PREFERRED_MIN_WIDTH = 1200
DETAIL_CONTENT_MAX_WIDTH = 1120

DETAIL_POSTER_WIDTH = 340
DETAIL_POSTER_HEIGHT = 500
DETAIL_POSTER_RADIUS = 16
DETAIL_POSTER_BORDER_WIDTH = 1
DETAIL_POSTER_RIGHT_GAP = 42

DETAIL_INFO_MIN_WIDTH = 350
DETAIL_INFO_MAX_WIDTH = 760
DETAIL_INFO_COLUMN_MAX_WIDTH = 700
DETAIL_INFO_TOP_OFFSET = 18

DETAIL_TITLE_FONT_FAMILY = FONT_FAMILY
DETAIL_TITLE_FONT_FALLBACK = FONT_FAMILY_FALLBACK
DETAIL_TITLE_FONT_SIZE = 32
DETAIL_TITLE_LINE_HEIGHT = 42
DETAIL_TITLE_MAX_LINES = 2

DETAIL_CHIP_HEIGHT = 36
DETAIL_CHIP_RADIUS = 18
DETAIL_CHIP_H_PADDING = 16
DETAIL_CHIP_FONT_SIZE = 15
DETAIL_CHIP_ROW_GAP = 10
DETAIL_CHIP_COL_GAP = 14
DETAIL_CHIP_MAX_ROWS = 2
DETAIL_CHIP_MAX_WIDTH = 210

DETAIL_SCORE_ROW_TOP_GAP = 34
DETAIL_RATING_WIDGET_SIZE = 136
DETAIL_RATING_CIRCLE_DIAMETER = 122
DETAIL_STARS_LEFT_GAP = 52
DETAIL_STAR_SIZE = 36
DETAIL_STAR_GAP = 9

DETAIL_USER_SCORE_BADGE_MIN_WIDTH = 64
DETAIL_USER_SCORE_BADGE_HEIGHT = 34
DETAIL_USER_SCORE_BADGE_RADIUS = 17
DETAIL_USER_SCORE_BADGE_FONT_SIZE = 15
DETAIL_USER_SCORE_BADGE_TOP = 14
DETAIL_USER_SCORE_BADGE_LEFT = 14
DETAIL_USER_SCORE_BADGE_PADDING_X = 9

DETAIL_MAIN_INFO_TOP_GAP = 38
DETAIL_MAIN_INFO_PANEL_RADIUS = 16
DETAIL_MAIN_INFO_PANEL_PADDING_X = 28
DETAIL_MAIN_INFO_PANEL_PADDING_Y = 18
DETAIL_MAIN_INFO_ROW_HEIGHT = 48
DETAIL_MAIN_INFO_ROW_GAP = 10
DETAIL_MAIN_INFO_HEADER_PANEL_GAP = 20
DETAIL_MAIN_INFO_LABEL_WIDTH = 230

DETAIL_OVERVIEW_TOP_GAP = 14
DETAIL_OVERVIEW_LEFT_INSET = 0
DETAIL_OVERVIEW_TITLE_TOP_GAP = 14
DETAIL_OVERVIEW_TEXT_TOP_GAP = 20
DETAIL_OVERVIEW_MAX_LINES_COLLAPSED = 4
DETAIL_OVERVIEW_MAX_WIDTH = DETAIL_POSTER_WIDTH
DETAIL_TITLE_CHIPS_GAP = 30
DETAIL_SCORE_MAIN_INFO_GAP = 24
DETAIL_SECTION_MAX_WIDTH = 920


TRANSPARENT_STYLE = "background: transparent;"


def px(value: int | float) -> int:
    """Scale a visual geometry token for QSS or widget layout."""
    return layout_px(value)


def layout_px(value: int | float) -> int:
    """Scale app layout geometry."""
    return _layout_px(value)


def control_px(value: int | float) -> int:
    """Scale interactive controls, inputs, tabs and chips."""
    return _control_px(value)


def list_px(value: int | float) -> int:
    """Scale list geometry."""
    return _list_px(value)


def detail_px(value: int | float) -> int:
    """Scale detail-card geometry."""
    return _detail_px(value)


def poster_px(value: int | float) -> int:
    """Scale poster geometry."""
    return _poster_px(value)


def font_px(value: int | float) -> int:
    """Scale a visual font token for QSS or QFont."""
    return _font_px(value)


# Layout constants are defined in desktop.theme.layout and re-exported here for compatibility.
from desktop.theme.layout import *  # noqa: E402,F403

__all__ = [
    "COLOR_BG",
    "COLOR_SURFACE",
    "COLOR_CARD",
    "COLOR_CARD_ALT",
    "COLOR_CARD_ELEVATED",
    "COLOR_HOVER",
    "COLOR_CONTROL_HOVER",
    "COLOR_BORDER",
    "COLOR_BORDER_HOVER",
    "COLOR_BORDER_ACTIVE",
    "COLOR_DIVIDER",
    "COLOR_TEXT",
    "COLOR_TEXT_SECONDARY",
    "COLOR_TEXT_MUTED",
    "COLOR_TEXT_SOFT",
    "COLOR_TEXT_CHIP",
    "COLOR_TEXT_INVERTED",
    "COLOR_ACCENT",
    "COLOR_ACCENT_HOVER",
    "COLOR_ACCENT_SOFT",
    "COLOR_ACCENT_PLOT_HOVER",
    "COLOR_ACCENT_PLOT_FILL",
    "COLOR_SELECTED_BG",
    "COLOR_SELECTED_BORDER",
    "COLOR_FOCUS_BORDER",
    "COLOR_ADD_BUTTON",
    "COLOR_ADD_BUTTON_BORDER",
    "COLOR_ADD_BUTTON_TOP",
    "COLOR_ADD_BUTTON_HOVER",
    "COLOR_ADD_BUTTON_HOVER_TOP",
    "COLOR_RATING",
    "COLOR_RATING_HOVER",
    "COLOR_STAR_ACTIVE",
    "COLOR_STAR_INACTIVE",
    "COLOR_SCORE_BADGE_BG",
    "COLOR_SCORE_BADGE_BORDER",
    "COLOR_SUCCESS",
    "COLOR_SUCCESS_SOFT",
    "COLOR_DELETE_BUTTON",
    "COLOR_DELETE_BUTTON_HOVER",
    "COLOR_STALE_BG",
    "COLOR_STALE_BORDER",
    "COLOR_STALE_TEXT",
    "COLOR_IMDB_ACCENT",
    "COLOR_KP_ACCENT",
    "COLOR_DETAIL_HERO_BG_TOP",
    "COLOR_DETAIL_HERO_BG_BOTTOM",
    "COLOR_DETAIL_HERO_BG_END",
    "COLOR_DETAIL_HERO_BORDER",
    "COLOR_DETAIL_HERO_BORDER_SOFT",
    "COLOR_DETAIL_TITLE",
    "COLOR_DETAIL_SECTION_HEADER",
    "COLOR_DETAIL_SECTION_DIVIDER",
    "COLOR_DETAIL_LABEL",
    "COLOR_DETAIL_VALUE",
    "COLOR_DETAIL_OVERVIEW_TEXT",
    "COLOR_DETAIL_GLASS",
    "COLOR_DETAIL_GLASS_SOFT",
    "COLOR_DETAIL_ACTION_BG",
    "COLOR_DETAIL_ACTION_BG_HOVER",
    "COLOR_DETAIL_ACTION_BG_DISABLED",
    "COLOR_DETAIL_CHIP_BG",
    "COLOR_DETAIL_CHIP_BORDER",
    "FILM_WINDOW_BG",
    "FILM_SURFACE_0",
    "FILM_SURFACE_1",
    "FILM_SURFACE_2",
    "FILM_BORDER_WEAK",
    "FILM_BORDER",
    "FILM_BORDER_STRONG",
    "FILM_ACCENT",
    "FILM_ACCENT_HOVER",
    "FILM_ACCENT_PRESSED",
    "FILM_ACCENT_DIM",
    "FILM_TEXT",
    "FILM_TEXT_SUBTLE",
    "FILM_TEXT_MUTED",
    "FILM_CHIP_BG",
    "FILM_CHIP_BORDER",
    "FILM_CHIP_TEXT",
    "FILM_MOVIE_BADGE_BG",
    "FILM_MOVIE_BADGE_BORDER",
    "FILM_MOVIE_BADGE_TEXT",
    "FILM_SERIES_BADGE_BG",
    "FILM_SERIES_BADGE_BORDER",
    "FILM_SERIES_BADGE_TEXT",
    "FILM_RATING_TRACK",
    "FILM_RATING_VALUE",
    "FILM_STAR_ON",
    "FILM_STAR_OFF",
    "FILM_SCROLLBAR_BG",
    "FILM_SCROLLBAR_HANDLE",
    "FILM_SCROLLBAR_HANDLE_HOVER",
    "FILM_COLORS",
    "FONT_FAMILY",
    "FONT_FAMILY_FALLBACK",
    "FONT_FAMILY_QSS",
    "FONT_APP",
    "FONT_BASE",
    "FONT_SMALL",
    "FONT_TINY",
    "FONT_SECTION",
    "FONT_TITLE",
    "FONT_TITLE_LARGE",
    "FONT_DIALOG_TITLE",
    "FONT_KPI_VALUE",
    "FONT_DENSE_SCORE",
    "FONT_OVERVIEW_TITLE",
    "FONT_OVERVIEW_TEXT",
    "FONT_RATING_VALUE_POINT",
    "FONT_RATING_LABEL_POINT",
    "DETAIL_RATING_RING_VALUE_FONT_MIN",
    "DETAIL_RATING_RING_LABEL_FONT_MIN",
    "FONT_DETAIL_MAIN_INFO_HEADER",
    "FONT_DETAIL_MAIN_INFO_LABEL",
    "FONT_DETAIL_MAIN_INFO_VALUE",
    "FONT_DETAIL_OVERVIEW_TEXT",
    "RADIUS_CARD",
    "RADIUS_CARD_LARGE",
    "RADIUS_CHIP",
    "RADIUS_INPUT",
    "RADIUS_BUTTON",
    "RADIUS_BUTTON_SMALL",
    "RADIUS_LIST_ITEM",
    "RADIUS_SCROLLBAR",
    "RADIUS_BAR",
    "SPACING_XSMALL",
    "SPACING_SMALL",
    "SPACING_MEDIUM",
    "SPACING_LARGE",
    "SPACING_XLARGE",
    "SPACING_XXLARGE",
    "ROOT_MARGIN",
    "SECTION_PADDING",
    "CARD_PADDING",
    "OVERVIEW_SECTION_TOP_SPACING",
    "OVERVIEW_TITLE_DIVIDER_SPACING",
    "OVERVIEW_DIVIDER_TEXT_SPACING",
    "OVERVIEW_TEXT_LINE_HEIGHT",
    "INPUT_PADDING_Y",
    "INPUT_PADDING_X",
    "BUTTON_PADDING_Y",
    "BUTTON_PADDING_X",
    "LIST_TITLE_FONT_SIZE",
    "LIST_META_FONT_SIZE",
    "LIST_PLACEHOLDER_FONT_SIZE",
    "LIST_TITLE_BAND_HEIGHT",
    "LIST_META_BAND_HEIGHT",
    "LIST_FALLBACK_WIDTH",
    "LIST_CARD_CORNER_RADIUS",
    "LIST_THUMB_CORNER_RADIUS",
    "LIST_MIN_TEXT_WIDTH",
    "LIST_ROW_INSET_X",
    "LIST_ROW_INSET_Y",
    "LIST_ITEM_HEIGHT_BASE",
    "LIST_THUMB_WIDTH_BASE",
    "LIST_THUMB_HEIGHT_BASE",
    "LIST_ITEM_H_PADDING_BASE",
    "LIST_ITEM_V_PADDING_BASE",
    "LIST_TEXT_GAP_BASE",
    "SIDEBAR_MIN_WIDTH",
    "SIDEBAR_MAX_WIDTH",
    "SPLITTER_SIDEBAR_DEFAULT",
    "SPLITTER_DETAIL_DEFAULT",
    "MAIN_TAB_PANE_TOP_LIFT",
    "LEFT_PANEL_TAB_GAP",
    "LEFT_PANEL_TOP_COMPENSATION",
    "DETAIL_TAB_TOP_MARGIN",
    "WATCHED_TAB_MARGIN",
    "WATCHED_TAB_SPACING",
    "WATCHED_ADD_TITLE_MIN_HEIGHT",
    "WATCHED_ADD_TITLE_PADDING_Y",
    "WATCHED_SIDEBAR_LABEL_FONT",
    "CANDIDATE_LIST_MIN_WIDTH",
    "CANDIDATE_LIST_MAX_WIDTH",
    "CANDIDATE_ROOT_MARGIN",
    "CANDIDATE_ROOT_SPACING",
    "CANDIDATE_LIST_SPACING",
    "CANDIDATE_SORT_ROW_SPACING",
    "CANDIDATE_SPLITTER_LIST_DEFAULT",
    "CANDIDATE_SPLITTER_DETAIL_DEFAULT",
    "CANDIDATE_SORT_COMBO_MAX_WIDTH",
    "SEARCH_DIALOG_WIDTH",
    "SEARCH_DIALOG_HEIGHT",
    "SEARCH_DIALOG_HEIGHT_ACTIVE",
    "PREVIEW_DIALOG_WIDTH",
    "PREVIEW_DIALOG_HEIGHT",
    "PREVIEW_CARD_SCROLL_MIN_HEIGHT",
    "ADD_TITLE_COMPACT_POSTER_WIDTH",
    "ADD_TITLE_COMPACT_POSTER_HEIGHT",
    "ADD_TITLE_COMPACT_POSTER_RADIUS",
    "ADD_TITLE_COMPACT_CONTENT_GAP",
    "ADD_TITLE_COMPACT_SCORE_WIDGET_SIZE",
    "ADD_TITLE_COMPACT_SCORE_CIRCLE_DIAMETER",
    "SETTINGS_DIALOG_MIN_WIDTH",
    "DETAIL_HERO_CARD_RADIUS",
    "DETAIL_HERO_CARD_PADDING",
    "DETAIL_HERO_CARD_PADDING_TOP",
    "DETAIL_HERO_MIN_WIDTH",
    "DETAIL_HERO_PREFERRED_MIN_WIDTH",
    "DETAIL_CONTENT_MAX_WIDTH",
    "DETAIL_POSTER_WIDTH",
    "DETAIL_POSTER_HEIGHT",
    "DETAIL_POSTER_RADIUS",
    "DETAIL_POSTER_BORDER_WIDTH",
    "DETAIL_POSTER_RIGHT_GAP",
    "DETAIL_INFO_MIN_WIDTH",
    "DETAIL_INFO_MAX_WIDTH",
    "DETAIL_INFO_COLUMN_MAX_WIDTH",
    "DETAIL_INFO_TOP_OFFSET",
    "DETAIL_TITLE_FONT_FAMILY",
    "DETAIL_TITLE_FONT_FALLBACK",
    "DETAIL_TITLE_FONT_SIZE",
    "DETAIL_TITLE_LINE_HEIGHT",
    "DETAIL_TITLE_MAX_LINES",
    "DETAIL_CHIP_HEIGHT",
    "DETAIL_CHIP_RADIUS",
    "DETAIL_CHIP_H_PADDING",
    "DETAIL_CHIP_FONT_SIZE",
    "DETAIL_CHIP_ROW_GAP",
    "DETAIL_CHIP_COL_GAP",
    "DETAIL_CHIP_MAX_ROWS",
    "DETAIL_CHIP_MAX_WIDTH",
    "DETAIL_SCORE_ROW_TOP_GAP",
    "DETAIL_RATING_WIDGET_SIZE",
    "DETAIL_RATING_CIRCLE_DIAMETER",
    "DETAIL_STARS_LEFT_GAP",
    "DETAIL_STAR_SIZE",
    "DETAIL_STAR_GAP",
    "DETAIL_USER_SCORE_BADGE_MIN_WIDTH",
    "DETAIL_USER_SCORE_BADGE_HEIGHT",
    "DETAIL_USER_SCORE_BADGE_RADIUS",
    "DETAIL_USER_SCORE_BADGE_FONT_SIZE",
    "DETAIL_USER_SCORE_BADGE_TOP",
    "DETAIL_USER_SCORE_BADGE_LEFT",
    "DETAIL_USER_SCORE_BADGE_PADDING_X",
    "DETAIL_MAIN_INFO_TOP_GAP",
    "DETAIL_MAIN_INFO_PANEL_RADIUS",
    "DETAIL_MAIN_INFO_PANEL_PADDING_X",
    "DETAIL_MAIN_INFO_PANEL_PADDING_Y",
    "DETAIL_MAIN_INFO_ROW_HEIGHT",
    "DETAIL_MAIN_INFO_ROW_GAP",
    "DETAIL_MAIN_INFO_HEADER_PANEL_GAP",
    "DETAIL_MAIN_INFO_LABEL_WIDTH",
    "DETAIL_OVERVIEW_TOP_GAP",
    "DETAIL_OVERVIEW_LEFT_INSET",
    "DETAIL_OVERVIEW_TITLE_TOP_GAP",
    "DETAIL_OVERVIEW_TEXT_TOP_GAP",
    "DETAIL_OVERVIEW_MAX_LINES_COLLAPSED",
    "DETAIL_OVERVIEW_MAX_WIDTH",
    "DETAIL_TITLE_CHIPS_GAP",
    "DETAIL_SCORE_MAIN_INFO_GAP",
    "DETAIL_SECTION_MAX_WIDTH",
    "TRANSPARENT_STYLE",
    "px",
    "layout_px",
    "control_px",
    "list_px",
    "detail_px",
    "poster_px",
    "font_px",
]
