"""Deterministic onboarding candidate-pool autofill."""

from candidates.onboarding.autofill import (
    MAX_TMDB_REQUESTS,
    STARTER_POOL_MIN_ACCEPTABLE,
    STARTER_POOL_TARGET,
    AutofillResult,
    CandidateFetchBucket,
    OnboardingTasteProfile,
    TmdbAutofillClient,
    allocate_integer_quotas,
    build_fetch_buckets,
    media_weights,
    origin_weights,
    release_weights,
    run_onboarding_autofill,
    should_start_onboarding_autofill,
    vibe_weights,
)
from candidates.onboarding.taste_presets import (
    ANIMATION_MODE_ANIMATION_ONLY,
    ANIMATION_MODE_ANY,
    ANIMATION_MODE_LIVE_ACTION_ONLY,
    PRESET_ANIME,
    PRESET_K_DRAMA,
    TastePreset,
    get_taste_preset,
    manual_taste_preset,
)

__all__ = [
    "MAX_TMDB_REQUESTS",
    "STARTER_POOL_MIN_ACCEPTABLE",
    "STARTER_POOL_TARGET",
    "AutofillResult",
    "CandidateFetchBucket",
    "OnboardingTasteProfile",
    "TmdbAutofillClient",
    "allocate_integer_quotas",
    "build_fetch_buckets",
    "media_weights",
    "origin_weights",
    "release_weights",
    "run_onboarding_autofill",
    "should_start_onboarding_autofill",
    "vibe_weights",
    "ANIMATION_MODE_ANIMATION_ONLY",
    "ANIMATION_MODE_ANY",
    "ANIMATION_MODE_LIVE_ACTION_ONLY",
    "PRESET_ANIME",
    "PRESET_K_DRAMA",
    "TastePreset",
    "get_taste_preset",
    "manual_taste_preset",
]
